name: Deploy to WordPress.org Repository
on:
  release:
    # run only when a new release is published, but not when it's classified as a pre-release.
    types: [released]
jobs:
  deploy_to_wp_repository:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ env.SVN_USERNAME }}
        SVN_PASSWORD: ${{ env.SVN_PASSWORD }}
        SLUG: arabic-english-estimated-reading-time
